export { withComputedProps } from "./functions/componentPropsFunction"
export { useMakUi, MakUiProvider } from "./context/useMakUi"
export * from "./types/index"
export { mak } from "./elements/mak"
export * from "./functions/helpers"
export { componentWrapperLogic } from "./functions/componentWrapperLogic"
